### ISSUE TITLE
Various bugs in gauleg routine

### ISSUE THREAD

**Issue by mreineck** [mselig/libsharp-wrapper#4]
The routine "gauleg" in wrapper.pyx currently has several serious problems:

- In line 912(https://github.com/mselig/libsharp-wrapper/blob/master/wrapper.pyx#L912), the "abs" function from C is called, causing its argument to be truncated to integer before taking the absolute value. This leads to accepting the initial guess for the roots and immediately exits the iteration. Instead of "abs", the "fabs" function must be used.

- In line 74  (https://github.com/mselig/libsharp-wrapper/blob/master/wrapper.pyx#L74),
  `double abs(double)` (which is incorrect, since such a function does not exist in C) needs to be replaced by `double fabs(double)`.

- In line 894 (https://github.com/mselig/libsharp-wrapper/blob/master/wrapper.pyx#L894), the expression for imax should be changed to `imax=(nlat+1)/2`, and line 897 needs to be changed to
`for i in range(1,imax+1)`. If that is not done, the routine will only work for even values of `nlat`.

- in line 966 (https://github.com/mselig/libsharp-wrapper/blob/master/wrapper.pyx#L966), passing the same pointer to  `gauleg` twice is very dangerous. It happens to work for the current implementation, but very small internal changes to `gauleg` could break this.

**Comment by mselig** [comment]
thank you for the input!
* i was indeed not aware of the ```abs``` issue
* i believe we agreed on the limitation of even ```nlat```, did we not? either way, valid point
* pointer ... you are right

**Comment by mreineck** [comment]
I don't remember whether there was an agreement on `nlat` being even, but given that `nlat` should be `lmax+1`, and there is no compelling reason why `lmax` needs to be odd, we should probably lift this restriction.

I'll prepare a pull request during the next days!

**Comment by mselig** [comment]
thanks a lot! it is a pleasure working i with you ... as always
